DEBUG 2021-06-21 06:39:45.192 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-21 06:39:45.192 UTC: 	 Running on: Linux lxplus7107.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-21 06:39:45.192 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-21 06:39:45.192 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
DEBUG 2021-06-21 08:19:02.254 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-21 08:19:02.254 UTC: 	 Running on: Linux lxplus7107.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-21 08:19:02.254 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-21 08:19:02.256 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
INFO 2021-06-21 08:19:02.257 UTC: 	 Will use CRAB configuration file configs/za_cfg.py
DEBUG 2021-06-21 08:19:02.257 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-21 08:19:02.258 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-21 08:19:02.259 UTC: 	 Working area '/afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_ZA' already exists 
Please change the requestName in the config file
ERROR 2021-06-21 08:19:02.259 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_ZA' already exists 
Please change the requestName in the config file
INFO 2021-06-21 08:19:02.287 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-06-21 08:31:51.269 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-21 08:31:51.270 UTC: 	 Running on: Linux lxplus7107.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-21 08:31:51.270 UTC: 	 Executing command: 'purge'
DEBUG 2021-06-21 08:31:51.270 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-06-21 08:31:51.271 UTC: 	 Error: crab_SingleMuon_C is not a valid CRAB project directory.
ERROR 2021-06-21 08:31:51.271 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_SingleMuon_C is not a valid CRAB project directory.
INFO 2021-06-21 08:31:51.278 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-06-22 08:44:56.889 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 08:44:56.889 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 08:44:56.889 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 08:44:56.889 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-06-22 08:44:56.890 UTC: 	 Error: _B/ is not a valid CRAB project directory.
ERROR 2021-06-22 08:44:56.890 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: _B/ is not a valid CRAB project directory.
INFO 2021-06-22 08:44:56.926 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-06-22 08:47:21.059 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 08:47:21.060 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 08:47:21.060 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 08:47:21.060 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
DEBUG 2021-06-22 13:27:05.522 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 13:27:05.522 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 13:27:05.522 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 13:27:05.522 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-06-22 13:27:05.524 UTC: 	 Error: crab_DoubleMuon_BC is not a valid CRAB project directory.
ERROR 2021-06-22 13:27:05.524 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_DoubleMuon_BC is not a valid CRAB project directory.
INFO 2021-06-22 13:27:05.553 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-06-22 13:37:14.640 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 13:37:14.640 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 13:37:14.640 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 13:37:14.640 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-06-22 13:37:14.643 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_SingleMuon_F
ERROR 2021-06-22 13:37:14.643 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_SingleMuon_F
INFO 2021-06-22 13:37:14.649 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-06-23 06:26:24.944 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-23 06:26:24.944 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-23 06:26:24.945 UTC: 	 Executing command: 'purge'
DEBUG 2021-06-23 06:26:24.945 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-06-23 06:26:24.946 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_SingleEG_F
ERROR 2021-06-23 06:26:24.946 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_SingleEG_F
INFO 2021-06-23 06:26:25.260 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_2_22/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-07-14 13:57:40.778 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-14 13:57:40.778 UTC: 	 Running on: Linux lxplus783.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-14 13:57:40.778 UTC: 	 Executing command: 'kill'
DEBUG 2021-07-14 13:57:40.778 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-07-14 13:57:40.780 UTC: 	 Error: crab_ggZZ_2e2 is not a valid CRAB project directory.
ERROR 2021-07-14 13:57:40.780 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ggZZ_2e2 is not a valid CRAB project directory.
INFO 2021-07-14 13:57:40.784 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-07-14 13:58:51.244 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-14 13:58:51.244 UTC: 	 Running on: Linux lxplus783.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-14 13:58:51.244 UTC: 	 Executing command: 'status'
DEBUG 2021-07-14 13:58:51.244 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-07-14 13:58:51.246 UTC: 	 Error: crab_ggZZ_4 is not a valid CRAB project directory.
ERROR 2021-07-14 13:58:51.246 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ggZZ_4 is not a valid CRAB project directory.
INFO 2021-07-14 13:58:51.252 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-07-14 15:29:21.275 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-14 15:29:21.276 UTC: 	 Running on: Linux lxplus7102.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-14 15:29:21.276 UTC: 	 Executing command: 'status'
DEBUG 2021-07-14 15:29:21.276 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-07-14 15:29:21.277 UTC: 	 Error: crab_SingleMuon_FB is not a valid CRAB project directory.
ERROR 2021-07-14 15:29:21.277 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_SingleMuon_FB is not a valid CRAB project directory.
INFO 2021-07-14 15:29:21.300 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2021-07-15 06:36:20.067 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-15 06:36:20.067 UTC: 	 Running on: Linux lxplus797.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-15 06:36:20.067 UTC: 	 Executing command: 'status'
DEBUG 2021-07-15 06:36:20.068 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2021-07-15 06:36:20.069 UTC: 	 Error: crab_WZtoL is not a valid CRAB project directory.
ERROR 2021-07-15 06:36:20.069 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_WZtoL is not a valid CRAB project directory.
INFO 2021-07-15 06:36:20.095 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
